#!/bin/bash

dir="$1"
num=$2

if [ -d "$dir" ]; then
    for file in "$dir"/*; do
        if [[ -f "$file" && `wc -c < "$file"` > $num  ]]; then
            echo $file has more than $num symbols
        fi
    done
else
    echo "Directory $dir doesn't exist" >&2
fi